[package]
name = "idagent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
openpgp-card = "0.3.4"
openpgp-card-pcsc = "0.3.0"
pinentry = "0.5.0"
secrecy = "0.8.0"
which = "4.4.0"
