[package]
name = "idagent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
clap = "4.2.2"
did-web = "0.2.1"
openpgp-card = "0.3.4"
openpgp-card-pcsc = "0.3.0"
pinentry = "0.5.0"
prettytable-rs = "0.10.0"
secrecy = "0.8.0"
serde_json = "1.0.95"
ssi = "0.6.0"
tokio = { version = "1.27.0", features = ["full"] }
which = "4.4.0"
